export const SAVE_USER = 'SAVE_USER';
export const SAVE_FOLLOW = 'SAVE_FOLLOW';
export const TIMELINE_SHOW = 'TIMELINE_SHOW';
export const TIMELINE_HIDE = 'TIMELINE_HIDE';
export const TWEET_SHOW = 'TWEET_SHOW';
export const TWEET_HIDE = 'TWEET_HIDE';
export const SEARCH_SHOW = 'SEARCH_SHOW';
export const SEARCH_HIDE = 'SEARCH_HIDE';
export const FOLLOW_SHOW = 'FOLLOW_SHOW';
export const FOLLOW_HIDE = 'FOLLOW_HIDE';

export const CONPONENT_SHOW_HIDE = {
    'TIMELINE_SHOW' : 'TIMELINE_SHOW',
    'TIMELINE_HIDE' : 'TIMELINE_HIDE',
    'TWEET_SHOW' : 'TWEET_SHOW',
    'TWEET_HIDE' : 'TWEET_HIDE',
    'SEARCH_SHOW' : 'SEARCH_SHOW',
    'SEARCH_HIDE' : 'SEARCH_HIDE',
    'FOLLOW_SHOW' : 'FOLLOW_SHOW',
    'FOLLOW_HIDE' : 'FOLLOW_HIDE'
};